schema_version = 1
name = "extension_name"
extension_config = "extension_config.cmake"
core_extensions = ["httpfs", "parquet"]
native_test_selection = "test/"

[vane]
repository = "AstroVela/vane"
revision = "0000000000000000000000000000000000000000"
